Repository OpenEMS/openems, pull requests merged in 2024-10, with the labels that each got.

#2837 Fix some UI display error
  ui/src/app/edge/live/common/storage/storage.component.html
  ui/src/app/edge/live/energymonitor/chart/chart.component.html
  ui/src/app/shared/components/flat/flat-widget-percentagebar/flat-widget-percentagebar.html
  ui/src/app/shared/components/flat/flat-widget-percentagebar/flat-widget-percentagebar.ts
Labels: Type: Bug, Component: UI

#2844 fix: Delete the duplicate button
  ui/src/app/shared/components/header/header.component.html
Labels: Component: UI

#2731 Unify icon styling
  ui/src/app/edge/live/Controller/Channelthreshold/Channelthreshold.html
  ui/src/app/edge/live/Controller/ChpSoc/ChpSoc.html
  ui/src/app/edge/live/Controller/Io/ChannelSingleThreshold/Io_ChannelSingleThreshold.html
  ui/src/app/edge/live/Controller/Io/ChannelSingleThreshold/Io_ChannelSingleThreshold.ts
  ui/src/app/shared/components/flat/flat-widget.component.html
  ui/src/app/shared/components/flat/flat.html
  ui/src/app/shared/components/flat/flat.ts
  ui/src/app/shared/type/widget.ts
  ui/src/global.scss
Labels: Type: Enhancement, Component: UI
